site_name: Cloud Credentials Field Manual
site_url: https://datadog.github.io/cloud-credentials-field-manual
repo_url: https://github.com/DataDog/cloud-credentials-field-manual
repo_name: datadog/cloud-credentials-field-manual
plugins:
  - search
  - awesome-pages
theme:
  name: material
  logo: ./logo.png
  favicon: ./logo-square.png
  palette:
    primary: dark-blue
  features:
  - navigation.expand
  - navigation.indexes
  - navigation.top
  - navigation.tabs
  - navigation.tabs.sticky
  - content.code.copy
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
use_directory_urls: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink
  - tables
  - meta
  - abbr
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true 
extra_css:
  - css/extra.css
copyright: Copyright 2025-Present Datadog, Inc.
nav:
  - Home: index.md
  - Extract cloud credentials from applications: 
    - Credentials delivery mechanisms: extract/types-of-credentials-delivery.md
    - ... | extract/**/*.md
  - Use cloud credentials:
    - AWS access keys: use/aws.md
    - Google Cloud tokens: use/gcp.md
    - Azure tokens: use/azure.md